// Package provisioning generates agent install scripts for Linux, Windows, and macOS.
// Scripts are served as plain text over HTTP and perform a fully unattended setup.
package provisioning

import (
	"fmt"
	"net/http"
	"strings"
)

// Platform identifies the target operating system and architecture pairing.
type Platform string

const (
	PlatformLinuxAMD64 Platform = "linux-amd64"
	PlatformLinuxARM64 Platform = "linux-arm64"
	PlatformWindows    Platform = "windows"
	PlatformMacOS      Platform = "macos"
)

// InstallConfig carries all tenant-specific values that are embedded into install scripts.
type InstallConfig struct {
	TenantID        string
	AgentType       string
	RegistrationURL string
	NATSUrl         string
	VaultAddr       string
	BinaryURL       string
	ChecksumURL     string
	AgentID         string
	FingerPrint     string
}

// GenerateLinuxScript returns a bash script that installs and registers the Kubric agent
// on Debian/RHEL compatible Linux distributions with systemd.
func GenerateLinuxScript(cfg InstallConfig) string {
	return fmt.Sprintf(`#!/usr/bin/env bash
# Kubric Agent Linux Installer
# Tenant: %s   Agent Type: %s
# Generated by Kubric provisioning service — do not edit manually.
set -euo pipefail

KUBRIC_DIR="/opt/kubric-agent"
CONF_DIR="/etc/kubric"
BINARY="$KUBRIC_DIR/kubric-agent"
SERVICE_NAME="kubric-agent"
REGISTRATION_URL=%q
NATS_URL=%q
VAULT_ADDR=%q
BINARY_URL=%q
CHECKSUM_URL=%q
TENANT_ID=%q
AGENT_TYPE=%q

# ── Prerequisites ────────────────────────────────────────────────────────────
command -v curl >/dev/null 2>&1 || { echo "ERROR: curl is required"; exit 1; }
command -v sha256sum >/dev/null 2>&1 || command -v shasum >/dev/null 2>&1 || \
  { echo "ERROR: sha256sum / shasum is required"; exit 1; }

# ── Architecture detection ───────────────────────────────────────────────────
ARCH=$(uname -m)
case "$ARCH" in
  x86_64)  ARCH_TAG="amd64" ;;
  aarch64) ARCH_TAG="arm64" ;;
  armv7l)  ARCH_TAG="armv7" ;;
  *)       echo "ERROR: Unsupported architecture: $ARCH"; exit 1 ;;
esac
echo "[kubric] Detected architecture: $ARCH_TAG"

# ── Directory setup ──────────────────────────────────────────────────────────
echo "[kubric] Creating directories..."
install -d -m 0750 "$KUBRIC_DIR"
install -d -m 0750 "$CONF_DIR"

# ── Download binary ──────────────────────────────────────────────────────────
TMP_BINARY=$(mktemp)
TMP_CHECKSUM=$(mktemp)
trap 'rm -f "$TMP_BINARY" "$TMP_CHECKSUM"' EXIT

FULL_URL="${BINARY_URL}-${ARCH_TAG}"
echo "[kubric] Downloading binary from $FULL_URL ..."
curl -fsSL --retry 5 --retry-delay 2 -o "$TMP_BINARY" "$FULL_URL"

# ── Blake3/SHA-256 checksum verification ─────────────────────────────────────
echo "[kubric] Verifying checksum..."
curl -fsSL --retry 3 -o "$TMP_CHECKSUM" "$CHECKSUM_URL"
EXPECTED=$(grep "${ARCH_TAG}" "$TMP_CHECKSUM" | awk '{print $1}')
if [ -z "$EXPECTED" ]; then
  echo "ERROR: Could not find checksum for $ARCH_TAG in $CHECKSUM_URL"
  exit 1
fi
ACTUAL=$(sha256sum "$TMP_BINARY" | awk '{print $1}')
if [ "$ACTUAL" != "$EXPECTED" ]; then
  echo "ERROR: Checksum mismatch! Expected $EXPECTED, got $ACTUAL"
  exit 1
fi
echo "[kubric] Checksum OK: $ACTUAL"

# ── Install binary ───────────────────────────────────────────────────────────
install -m 0750 "$TMP_BINARY" "$BINARY"
echo "[kubric] Binary installed to $BINARY"

# ── Fingerprint this machine ─────────────────────────────────────────────────
echo "[kubric] Collecting hardware fingerprint..."
FINGERPRINT=$("$BINARY" fingerprint 2>/dev/null || echo "")
if [ -z "$FINGERPRINT" ]; then
  echo "WARNING: Could not collect fingerprint; using hostname-based fallback"
  FINGERPRINT=$(hostname | sha256sum | awk '{print $1}')
fi
echo "[kubric] Fingerprint: $FINGERPRINT"

# ── Register with provisioning server ───────────────────────────────────────
echo "[kubric] Registering agent..."
REG_RESPONSE=$(curl -fsSL --retry 3 --retry-delay 5 \
  -X POST "$REGISTRATION_URL" \
  -H "Content-Type: application/json" \
  -d "{
    \"agent_type\":   \"$AGENT_TYPE\",
    \"fingerprint\":  \"$FINGERPRINT\",
    \"hostname\":     \"$(hostname)\",
    \"os\":           \"linux\",
    \"kernel\":       \"$(uname -r)\",
    \"arch\":         \"$ARCH_TAG\",
    \"nats_url\":     \"$NATS_URL\"
  }")

AGENT_ID=$(echo "$REG_RESPONSE"    | grep -o '"agent_id":"[^"]*"'    | cut -d'"' -f4)
NATS_CREDS=$(echo "$REG_RESPONSE"  | grep -o '"nats_credentials":"[^"]*"' | cut -d'"' -f4)
VAULT_ROLE=$(echo "$REG_RESPONSE"  | grep -o '"vault_role_id":"[^"]*"'    | cut -d'"' -f4)
VAULT_SECRET=$(echo "$REG_RESPONSE"| grep -o '"vault_secret_id":"[^"]*"'  | cut -d'"' -f4)

if [ -z "$AGENT_ID" ]; then
  echo "ERROR: Registration failed. Response: $REG_RESPONSE"
  exit 1
fi
echo "[kubric] Registered successfully. agent_id=$AGENT_ID"

# ── Write config file ────────────────────────────────────────────────────────
cat >"$CONF_DIR/agent.conf" <<AGENTCONF
AGENT_ID=$AGENT_ID
TENANT_ID=$TENANT_ID
AGENT_TYPE=$AGENT_TYPE
NATS_URL=$NATS_URL
VAULT_ADDR=$VAULT_ADDR
VAULT_ROLE_ID=$VAULT_ROLE
VAULT_SECRET_ID=$VAULT_SECRET
FINGERPRINT=$FINGERPRINT
AGENTCONF
chmod 0640 "$CONF_DIR/agent.conf"

# Write NATS credentials
printf "%%s" "$NATS_CREDS" | sed 's/\\n/\n/g' > "$CONF_DIR/nats.creds"
chmod 0640 "$CONF_DIR/nats.creds"

# ── systemd unit file ────────────────────────────────────────────────────────
cat >/etc/systemd/system/${SERVICE_NAME}.service <<UNIT
[Unit]
Description=Kubric Security Agent (%s)
Documentation=https://docs.kubric.io/agents
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=/etc/kubric/agent.conf
ExecStart=/opt/kubric-agent/kubric-agent
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal
SyslogIdentifier=kubric-agent
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/log/kubric /tmp
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_RAW CAP_SYS_PTRACE

[Install]
WantedBy=multi-user.target
UNIT

# ── Enable and start ─────────────────────────────────────────────────────────
systemctl daemon-reload
systemctl enable --now "$SERVICE_NAME"
echo "[kubric] Service started. Status:"
systemctl status "$SERVICE_NAME" --no-pager || true
echo "[kubric] Installation complete."
`,
		cfg.TenantID, cfg.AgentType,
		cfg.RegistrationURL, cfg.NATSUrl, cfg.VaultAddr,
		cfg.BinaryURL, cfg.ChecksumURL,
		cfg.TenantID, cfg.AgentType,
		cfg.AgentType,
	)
}

// GenerateWindowsScript returns a PowerShell script that installs and registers the
// Kubric agent on Windows using NSSM (Non-Sucking Service Manager) as the service wrapper.
func GenerateWindowsScript(cfg InstallConfig) string {
	return fmt.Sprintf(`#Requires -RunAsAdministrator
# Kubric Agent Windows Installer
# Tenant: %s   Agent Type: %s
# Generated by Kubric provisioning service — do not edit manually.
Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$KubricDir  = "C:\Program Files\Kubric\Agent"
$ConfDir    = "C:\ProgramData\Kubric"
$BinaryPath = Join-Path $KubricDir "kubric-agent.exe"
$ServiceName    = "KubricAgent"
$RegistrationURL= %q
$NatsURL        = %q
$VaultAddr      = %q
$BinaryURL      = %q
$ChecksumURL    = %q
$TenantID       = %q
$AgentType      = %q

# ── Directory setup ──────────────────────────────────────────────────────────
Write-Host "[kubric] Creating directories..."
$null = New-Item -ItemType Directory -Force -Path $KubricDir
$null = New-Item -ItemType Directory -Force -Path $ConfDir

# ── Architecture detection ───────────────────────────────────────────────────
$ArchTag = if ([System.Environment]::Is64BitOperatingSystem) { "amd64" } else { "386" }
if ($env:PROCESSOR_ARCHITECTURE -eq "ARM64") { $ArchTag = "arm64" }
Write-Host "[kubric] Architecture: $ArchTag"

# ── Download binary ──────────────────────────────────────────────────────────
$TmpBinary   = Join-Path $env:TEMP "kubric-agent-$ArchTag.exe"
$TmpChecksum = Join-Path $env:TEMP "kubric-checksums.txt"
$FullURL = "$BinaryURL-$ArchTag.exe"
Write-Host "[kubric] Downloading binary from $FullURL ..."
Invoke-WebRequest -Uri $FullURL -OutFile $TmpBinary -UseBasicParsing

# ── Checksum verification ─────────────────────────────────────────────────────
Write-Host "[kubric] Verifying checksum..."
Invoke-WebRequest -Uri $ChecksumURL -OutFile $TmpChecksum -UseBasicParsing
$ExpectedLine = Get-Content $TmpChecksum | Where-Object { $_ -match $ArchTag }
if (-not $ExpectedLine) { throw "Could not find checksum for $ArchTag" }
$Expected = ($ExpectedLine -split '\s+')[0]
$Hash     = (Get-FileHash -Algorithm SHA256 -Path $TmpBinary).Hash.ToLower()
if ($Hash -ne $Expected) { throw "Checksum mismatch: expected $Expected got $Hash" }
Write-Host "[kubric] Checksum OK: $Hash"

# ── Install binary ───────────────────────────────────────────────────────────
Copy-Item -Force $TmpBinary $BinaryPath
Write-Host "[kubric] Binary installed to $BinaryPath"

# ── Fingerprint ──────────────────────────────────────────────────────────────
Write-Host "[kubric] Collecting hardware fingerprint..."
$Fingerprint = & $BinaryPath fingerprint 2>$null
if (-not $Fingerprint) {
  $Fingerprint = (Get-WmiObject Win32_ComputerSystemProduct).UUID
}
Write-Host "[kubric] Fingerprint: $Fingerprint"

# ── Registration ─────────────────────────────────────────────────────────────
Write-Host "[kubric] Registering agent..."
$Body = @{
  agent_type  = $AgentType
  fingerprint = $Fingerprint
  hostname    = $env:COMPUTERNAME
  os          = "windows"
  kernel      = (Get-WmiObject Win32_OperatingSystem).Version
  arch        = $ArchTag
  nats_url    = $NatsURL
} | ConvertTo-Json
$Params = @{ Method = "POST"; Uri = $RegistrationURL; ContentType = "application/json"; Body = $Body }
$Response = Invoke-RestMethod @Params
$AgentID    = $Response.agent_id
$VaultRole  = $Response.vault_role_id
$VaultSec   = $Response.vault_secret_id
$NatsCreds  = $Response.nats_credentials
if (-not $AgentID) { throw "Registration failed: $Response" }
Write-Host "[kubric] Registered. agent_id=$AgentID"

# ── Write config ──────────────────────────────────────────────────────────────
$Config = @"
AGENT_ID=$AgentID
TENANT_ID=$TenantID
AGENT_TYPE=$AgentType
NATS_URL=$NatsURL
VAULT_ADDR=$VaultAddr
VAULT_ROLE_ID=$VaultRole
VAULT_SECRET_ID=$VaultSec
FINGERPRINT=$Fingerprint
"@
$Config | Set-Content -Path (Join-Path $ConfDir "agent.conf") -Encoding UTF8
$NatsCreds | Set-Content -Path (Join-Path $ConfDir "nats.creds") -Encoding UTF8
Write-Host "[kubric] Config written to $ConfDir"

# ── Windows Service via sc.exe ────────────────────────────────────────────────
Write-Host "[kubric] Creating Windows service '$ServiceName'..."
sc.exe create $ServiceName binPath= ('"' + $BinaryPath + '"') start= auto obj= LocalSystem DisplayName= "Kubric Security Agent" | Out-Null
sc.exe description $ServiceName "Kubric Security Agent - Tenant %s" | Out-Null
sc.exe start $ServiceName | Out-Null
Write-Host "[kubric] Service started."
Write-Host "[kubric] Installation complete."
`,
		cfg.TenantID, cfg.AgentType,
		cfg.RegistrationURL, cfg.NATSUrl, cfg.VaultAddr,
		cfg.BinaryURL, cfg.ChecksumURL,
		cfg.TenantID, cfg.AgentType,
		cfg.TenantID,
	)
}

// GenerateMacOSScript returns a bash script that installs the Kubric agent
// on macOS using a launchd plist for service management.
func GenerateMacOSScript(cfg InstallConfig) string {
	return fmt.Sprintf(`#!/usr/bin/env bash
# Kubric Agent macOS Installer
# Tenant: %s   Agent Type: %s
# Generated by Kubric provisioning service — do not edit manually.
set -euo pipefail

KUBRIC_DIR="/usr/local/opt/kubric-agent"
CONF_DIR="/etc/kubric"
BINARY="$KUBRIC_DIR/kubric-agent"
PLIST_PATH="/Library/LaunchDaemons/io.kubric.agent.plist"
REGISTRATION_URL=%q
NATS_URL=%q
VAULT_ADDR=%q
BINARY_URL=%q
CHECKSUM_URL=%q
TENANT_ID=%q
AGENT_TYPE=%q

# ── Prerequisites ─────────────────────────────────────────────────────────────
command -v curl    >/dev/null 2>&1 || { echo "ERROR: curl required"; exit 1; }
command -v shasum  >/dev/null 2>&1 || { echo "ERROR: shasum required"; exit 1; }

# ── Architecture ──────────────────────────────────────────────────────────────
ARCH=$(uname -m)
case "$ARCH" in
  x86_64)  ARCH_TAG="amd64" ;;
  arm64)   ARCH_TAG="arm64" ;;
  *)       echo "ERROR: Unsupported architecture: $ARCH"; exit 1 ;;
esac
echo "[kubric] Architecture: $ARCH_TAG"

# ── Directories ───────────────────────────────────────────────────────────────
sudo mkdir -p "$KUBRIC_DIR" "$CONF_DIR"
sudo chmod 750 "$KUBRIC_DIR" "$CONF_DIR"

# ── Download and verify ───────────────────────────────────────────────────────
TMP_BINARY=$(mktemp)
TMP_CHECKSUM=$(mktemp)
trap 'rm -f "$TMP_BINARY" "$TMP_CHECKSUM"' EXIT

FULL_URL="${BINARY_URL}-${ARCH_TAG}-darwin"
echo "[kubric] Downloading $FULL_URL ..."
curl -fsSL --retry 5 --retry-delay 2 -o "$TMP_BINARY" "$FULL_URL"

echo "[kubric] Verifying checksum..."
curl -fsSL --retry 3 -o "$TMP_CHECKSUM" "$CHECKSUM_URL"
EXPECTED=$(grep "${ARCH_TAG}-darwin" "$TMP_CHECKSUM" | awk '{print $1}')
if [ -z "$EXPECTED" ]; then
  echo "ERROR: no checksum found for ${ARCH_TAG}-darwin"
  exit 1
fi
ACTUAL=$(shasum -a 256 "$TMP_BINARY" | awk '{print $1}')
[ "$ACTUAL" = "$EXPECTED" ] || { echo "ERROR: checksum mismatch"; exit 1; }
echo "[kubric] Checksum OK"

sudo install -m 750 "$TMP_BINARY" "$BINARY"

# ── Fingerprint and register ──────────────────────────────────────────────────
echo "[kubric] Collecting fingerprint..."
FINGERPRINT=$("$BINARY" fingerprint 2>/dev/null || \
  system_profiler SPHardwareDataType 2>/dev/null | grep 'Hardware UUID' | awk '{print $NF}' | \
  shasum -a 256 | awk '{print $1}')
echo "[kubric] Fingerprint: $FINGERPRINT"

echo "[kubric] Registering..."
REG_RESPONSE=$(curl -fsSL --retry 3 \
  -X POST "$REGISTRATION_URL" \
  -H "Content-Type: application/json" \
  -d "{
    \"agent_type\":  \"$AGENT_TYPE\",
    \"fingerprint\": \"$FINGERPRINT\",
    \"hostname\":    \"$(hostname)\",
    \"os\":          \"darwin\",
    \"kernel\":      \"$(uname -r)\",
    \"arch\":        \"$ARCH_TAG\",
    \"nats_url\":    \"$NATS_URL\"
  }")

AGENT_ID=$(echo    "$REG_RESPONSE" | python3 -c "import sys,json;d=json.load(sys.stdin);print(d.get('agent_id',''))" 2>/dev/null)
VAULT_ROLE=$(echo  "$REG_RESPONSE" | python3 -c "import sys,json;d=json.load(sys.stdin);print(d.get('vault_role_id',''))" 2>/dev/null)
VAULT_SEC=$(echo   "$REG_RESPONSE" | python3 -c "import sys,json;d=json.load(sys.stdin);print(d.get('vault_secret_id',''))" 2>/dev/null)
NATS_CREDS=$(echo  "$REG_RESPONSE" | python3 -c "import sys,json;d=json.load(sys.stdin);print(d.get('nats_credentials',''))" 2>/dev/null)

[ -n "$AGENT_ID" ] || { echo "ERROR: registration failed: $REG_RESPONSE"; exit 1; }
echo "[kubric] Registered. agent_id=$AGENT_ID"

# ── Write config ──────────────────────────────────────────────────────────────
sudo tee "$CONF_DIR/agent.conf" <<AGENTCONF >/dev/null
AGENT_ID=$AGENT_ID
TENANT_ID=$TENANT_ID
AGENT_TYPE=$AGENT_TYPE
NATS_URL=$NATS_URL
VAULT_ADDR=$VAULT_ADDR
VAULT_ROLE_ID=$VAULT_ROLE
VAULT_SECRET_ID=$VAULT_SEC
FINGERPRINT=$FINGERPRINT
AGENTCONF
sudo chmod 640 "$CONF_DIR/agent.conf"
printf "%%s" "$NATS_CREDS" | sudo tee "$CONF_DIR/nats.creds" >/dev/null
sudo chmod 640 "$CONF_DIR/nats.creds"

# ── launchd plist ─────────────────────────────────────────────────────────────
sudo tee "$PLIST_PATH" <<PLIST >/dev/null
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>             <string>io.kubric.agent</string>
  <key>ProgramArguments</key>  <array><string>$BINARY</string></array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>AGENT_ID</key>          <string>$AGENT_ID</string>
    <key>TENANT_ID</key>         <string>$TENANT_ID</string>
    <key>NATS_URL</key>          <string>$NATS_URL</string>
    <key>VAULT_ADDR</key>        <string>$VAULT_ADDR</string>
    <key>VAULT_ROLE_ID</key>     <string>$VAULT_ROLE</string>
    <key>VAULT_SECRET_ID</key>   <string>$VAULT_SEC</string>
  </dict>
  <key>RunAtLoad</key>         <true/>
  <key>KeepAlive</key>         <true/>
  <key>StandardOutPath</key>   <string>/var/log/kubric-agent.log</string>
  <key>StandardErrorPath</key> <string>/var/log/kubric-agent.err</string>
</dict>
</plist>
PLIST
sudo chmod 644 "$PLIST_PATH"
sudo launchctl load -w "$PLIST_PATH"
echo "[kubric] launchd service loaded."
echo "[kubric] Installation complete."
`,
		cfg.TenantID, cfg.AgentType,
		cfg.RegistrationURL, cfg.NATSUrl, cfg.VaultAddr,
		cfg.BinaryURL, cfg.ChecksumURL,
		cfg.TenantID, cfg.AgentType,
	)
}

// ScriptHandler is an http.Handler that serves install scripts as plain text.
//
//	GET /install/{platform}?tenant_id=...&agent_type=...&registration_url=...
type ScriptHandler struct {
	vaultAddr string
	natsURL   string
	binaryURL string
}

// NewScriptHandler creates a ScriptHandler.
func NewScriptHandler(vaultAddr, natsURL, binaryURL string) *ScriptHandler {
	return &ScriptHandler{vaultAddr: vaultAddr, natsURL: natsURL, binaryURL: binaryURL}
}

// ServeHTTP dispatches to the platform-specific generator.
func (h *ScriptHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	// Extract platform from path: /install/linux-amd64  ->  "linux-amd64"
	pathParts := strings.Split(strings.Trim(r.URL.Path, "/"), "/")
	if len(pathParts) < 2 {
		http.Error(w, "missing platform in path: /install/{platform}", http.StatusBadRequest)
		return
	}
	platform := Platform(pathParts[len(pathParts)-1])

	q := r.URL.Query()
	tenantID        := q.Get("tenant_id")
	agentType       := q.Get("agent_type")
	registrationURL := q.Get("registration_url")

	var missing []string
	if tenantID == ""        { missing = append(missing, "tenant_id") }
	if agentType == ""       { missing = append(missing, "agent_type") }
	if registrationURL == "" { missing = append(missing, "registration_url") }
	if len(missing) > 0 {
		http.Error(w, "missing required query parameters: "+strings.Join(missing, ", "), http.StatusBadRequest)
		return
	}

	cfg := InstallConfig{
		TenantID:        tenantID,
		AgentType:       agentType,
		RegistrationURL: registrationURL,
		NATSUrl:         h.natsURL,
		VaultAddr:       h.vaultAddr,
		BinaryURL:       h.binaryURL + "/" + agentType,
		ChecksumURL:     h.binaryURL + "/" + agentType + "/checksums.txt",
	}

	var script string
	var filename string
	switch platform {
	case PlatformLinuxAMD64, PlatformLinuxARM64:
		script = GenerateLinuxScript(cfg)
		filename = "install-kubric-agent.sh"
	case PlatformWindows:
		script = GenerateWindowsScript(cfg)
		filename = "install-kubric-agent.ps1"
	case PlatformMacOS:
		script = GenerateMacOSScript(cfg)
		filename = "install-kubric-agent-macos.sh"
	default:
		http.Error(w, fmt.Sprintf("unknown platform %q; valid choices: linux-amd64, linux-arm64, windows, macos", platform), http.StatusBadRequest)
		return
	}

	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("Content-Disposition", `attachment; filename="`+filename+`"`)
	w.Header().Set("Cache-Control", "no-store")
	w.WriteHeader(http.StatusOK)
	fmt.Fprint(w, script)
}
