-- =============================================================================
-- Migration 001 — Layer 0 Foundation Schema (L0-7)
-- =============================================================================
-- Applies to: Supabase / PostgreSQL 16+
-- Run:  psql $KUBRIC_DATABASE_URL -f 001_layer0_foundation.up.sql
-- Or:   docker exec -i kubric-postgres psql -U kubric -d kubric \
--          < db/migrations/001_layer0_foundation.up.sql
--
-- Design principles:
--   • tenant_id is NOT NULL on every table — enforced at DB level
--   • UUID primary keys generated by gen_random_uuid()
--   • Timestamps in TIMESTAMPTZ (UTC)
--   • Indexes on tenant_id for all tables
--   • RLS policies commented out; enable after testing
-- =============================================================================

BEGIN;

-- ─── Extensions ──────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "pgcrypto";   -- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "pg_trgm";    -- trigram indexes for CVE search

-- =============================================================================
-- Table 1: kubric_tenants (managed by K-SVC)
-- =============================================================================
CREATE TABLE IF NOT EXISTS kubric_tenants (
    tenant_id   TEXT        NOT NULL,
    name        TEXT        NOT NULL,
    plan        TEXT        NOT NULL DEFAULT 'starter',
    status      TEXT        NOT NULL DEFAULT 'active'
                            CHECK (status IN ('active','suspended','deleted')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT kubric_tenants_pkey PRIMARY KEY (tenant_id),
    CONSTRAINT kubric_tenants_id_format CHECK (
        tenant_id ~ '^[a-z0-9][a-z0-9\-]{0,61}[a-z0-9]$'
    )
);

CREATE INDEX IF NOT EXISTS kubric_tenants_status_idx ON kubric_tenants (status);

-- =============================================================================
-- Table 2: vdr_findings (managed by VDR)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vdr_findings (
    id          TEXT        NOT NULL DEFAULT gen_random_uuid()::text,
    tenant_id   TEXT        NOT NULL REFERENCES kubric_tenants(tenant_id) ON DELETE CASCADE,
    target      TEXT        NOT NULL,
    scanner     TEXT        NOT NULL CHECK (scanner IN ('nuclei','trivy','grype','manual')),
    severity    TEXT        NOT NULL CHECK (severity IN ('critical','high','medium','low','informational')),
    cve_id      TEXT        NOT NULL DEFAULT '',
    title       TEXT        NOT NULL,
    description TEXT        NOT NULL DEFAULT '',
    status      TEXT        NOT NULL DEFAULT 'open'
                            CHECK (status IN ('open','acknowledged','resolved','false-positive')),
    epss_score  NUMERIC(5,4),
    raw_json    TEXT        NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT vdr_findings_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS vdr_findings_tenant_id_idx  ON vdr_findings (tenant_id);
CREATE INDEX IF NOT EXISTS vdr_findings_severity_idx   ON vdr_findings (severity);
CREATE INDEX IF NOT EXISTS vdr_findings_status_idx     ON vdr_findings (status);
CREATE INDEX IF NOT EXISTS vdr_findings_cve_id_idx     ON vdr_findings (cve_id)
    WHERE cve_id <> '';

-- =============================================================================
-- Table 3: kic_assessments (managed by KIC)
-- =============================================================================
CREATE TABLE IF NOT EXISTS kic_assessments (
    id            TEXT        NOT NULL DEFAULT gen_random_uuid()::text,
    tenant_id     TEXT        NOT NULL REFERENCES kubric_tenants(tenant_id) ON DELETE CASCADE,
    framework     TEXT        NOT NULL,
    control_id    TEXT        NOT NULL,
    title         TEXT        NOT NULL,
    status        TEXT        NOT NULL DEFAULT 'not-reviewed'
                              CHECK (status IN ('pass','fail','not-applicable','not-reviewed')),
    evidence_json TEXT        NOT NULL DEFAULT '',
    assessed_by   TEXT        NOT NULL DEFAULT 'manual',
    assessed_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT kic_assessments_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS kic_assessments_tenant_id_idx ON kic_assessments (tenant_id);
CREATE INDEX IF NOT EXISTS kic_assessments_framework_idx ON kic_assessments (framework);
CREATE INDEX IF NOT EXISTS kic_assessments_status_idx    ON kic_assessments (status);

-- =============================================================================
-- Table 4: noc_clusters (managed by NOC)
-- =============================================================================
CREATE TABLE IF NOT EXISTS noc_clusters (
    id         TEXT        NOT NULL DEFAULT gen_random_uuid()::text,
    tenant_id  TEXT        NOT NULL REFERENCES kubric_tenants(tenant_id) ON DELETE CASCADE,
    name       TEXT        NOT NULL,
    provider   TEXT        NOT NULL DEFAULT 'k8s'
               CHECK (provider IN ('k8s','eks','gke','aks','proxmox')),
    version    TEXT        NOT NULL DEFAULT '',
    status     TEXT        NOT NULL DEFAULT 'unknown'
               CHECK (status IN ('healthy','degraded','critical','unknown')),
    last_seen  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT noc_clusters_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS noc_clusters_tenant_id_idx ON noc_clusters (tenant_id);

-- =============================================================================
-- Table 5: noc_agents (managed by NOC)
-- =============================================================================
CREATE TABLE IF NOT EXISTS noc_agents (
    id             TEXT        NOT NULL DEFAULT gen_random_uuid()::text,
    tenant_id      TEXT        NOT NULL REFERENCES kubric_tenants(tenant_id) ON DELETE CASCADE,
    cluster_id     TEXT        NOT NULL DEFAULT '',
    hostname       TEXT        NOT NULL,
    agent_type     TEXT        NOT NULL
                   CHECK (agent_type IN ('coresec','netguard','perftrace','watchdog')),
    version        TEXT        NOT NULL DEFAULT '',
    status         TEXT        NOT NULL DEFAULT 'online'
                   CHECK (status IN ('online','offline','degraded')),
    last_heartbeat TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT noc_agents_pkey PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS noc_agents_identity_idx
    ON noc_agents (tenant_id, hostname, agent_type);
CREATE INDEX IF NOT EXISTS noc_agents_tenant_id_idx ON noc_agents (tenant_id);

-- =============================================================================
-- Table 6: kai_triage_results (managed by KAI)
-- =============================================================================
CREATE TABLE IF NOT EXISTS kai_triage_results (
    triage_id          TEXT        NOT NULL DEFAULT gen_random_uuid()::text,
    tenant_id          TEXT        NOT NULL REFERENCES kubric_tenants(tenant_id) ON DELETE CASCADE,
    source_event_id    TEXT        NOT NULL DEFAULT '',
    source_subject     TEXT        NOT NULL DEFAULT '',
    timestamp          TIMESTAMPTZ NOT NULL DEFAULT now(),
    severity           TEXT        NOT NULL DEFAULT 'MEDIUM'
                       CHECK (severity IN ('CRITICAL','HIGH','MEDIUM','LOW','INFO')),
    mitre_techniques   TEXT[]      NOT NULL DEFAULT '{}',
    summary            TEXT        NOT NULL DEFAULT '',
    recommended_action TEXT        NOT NULL DEFAULT '',
    confidence         NUMERIC(4,3),
    model_used         TEXT        NOT NULL DEFAULT '',
    kiss_score         NUMERIC(5,2),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT kai_triage_results_pkey PRIMARY KEY (triage_id)
);

CREATE INDEX IF NOT EXISTS kai_triage_tenant_id_idx  ON kai_triage_results (tenant_id);
CREATE INDEX IF NOT EXISTS kai_triage_severity_idx   ON kai_triage_results (severity);
CREATE INDEX IF NOT EXISTS kai_triage_timestamp_idx  ON kai_triage_results (timestamp DESC);

-- =============================================================================
-- Table 7: feature_flags (LaunchDarkly-style, Layer 3+)
-- =============================================================================
CREATE TABLE IF NOT EXISTS feature_flags (
    flag_key    TEXT        NOT NULL,
    tenant_id   TEXT        NOT NULL DEFAULT '__global__',
    enabled     BOOLEAN     NOT NULL DEFAULT false,
    rollout_pct SMALLINT    NOT NULL DEFAULT 0 CHECK (rollout_pct BETWEEN 0 AND 100),
    config_json JSONB       NOT NULL DEFAULT '{}',
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT feature_flags_pkey PRIMARY KEY (flag_key, tenant_id)
);

CREATE INDEX IF NOT EXISTS feature_flags_tenant_idx ON feature_flags (tenant_id);

-- Insert default global flags
INSERT INTO feature_flags (flag_key, enabled, rollout_pct, config_json)
VALUES
    ('kai.triage.enabled',        true,  100, '{}'),
    ('kai.remediate.auto_apply',  false,   0, '{}'),
    ('layer3.sigma.enabled',      false,   0, '{}'),
    ('layer3.yara.enabled',       false,   0, '{}'),
    ('layer3.rita.enabled',       false,   0, '{}')
ON CONFLICT (flag_key, tenant_id) DO NOTHING;

-- =============================================================================
-- Table 8: agent_enrollment (L3 — agent bootstrap tokens)
-- =============================================================================
CREATE TABLE IF NOT EXISTS agent_enrollment (
    enrollment_id  TEXT        NOT NULL DEFAULT gen_random_uuid()::text,
    tenant_id      TEXT        NOT NULL REFERENCES kubric_tenants(tenant_id) ON DELETE CASCADE,
    agent_type     TEXT        NOT NULL
                   CHECK (agent_type IN ('coresec','netguard','perftrace','watchdog')),
    bootstrap_token TEXT       NOT NULL,          -- hashed; real token never stored
    token_hash     TEXT        NOT NULL UNIQUE,
    expires_at     TIMESTAMPTZ NOT NULL DEFAULT (now() + INTERVAL '24 hours'),
    claimed_at     TIMESTAMPTZ,
    claimed_agent_id TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT agent_enrollment_pkey PRIMARY KEY (enrollment_id)
);

CREATE INDEX IF NOT EXISTS agent_enrollment_tenant_idx  ON agent_enrollment (tenant_id);
CREATE INDEX IF NOT EXISTS agent_enrollment_expires_idx ON agent_enrollment (expires_at);

COMMIT;
