###############################################################################
# K-K8S-MESH-002  Linkerd Control-Plane Helm Values
# For use with: helm install linkerd-control-plane linkerd/linkerd-control-plane
###############################################################################
identity:
  issuer:
    scheme: kubernetes.io/tls
    clockSkewAllowance: 20s

proxyInit:
  runAsRoot: false
  iptablesMode: nft

controllerReplicas: 2

proxy:
  resources:
    cpu:
      request: 50m
      limit: 500m
    memory:
      request: 64Mi
      limit: 256Mi

dashboard:
  enabled: true
  replicas: 1

profileValidator:
  enabled: true

podMonitor:
  enabled: true
  controller:
    enabled: true

heartbeatSchedule: "0 0 * * *"

nodeSelector:
  kubernetes.io/os: linux

tolerations: []

enablePodAntiAffinity: true

webhookFailurePolicy: Fail
