resources:
  - name: source-repo
    type: git
    source:
      uri: https://github.com/managekube-hue/kubric.git
      branch: main

  - name: container-image
    type: registry-image
    source:
      repository: ghcr.io/managekube-hue/kubric-ksvc
      username: ((registry.username))
      password: ((registry.password))

jobs:
  - name: test-and-build
    plan:
      - get: source-repo
        trigger: true

      - task: test
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: golang
              tag: "1.22"
          inputs:
            - name: source-repo
          run:
            path: sh
            args:
              - -c
              - |
                cd source-repo
                go test -race ./...

      - task: build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: golang
              tag: "1.22"
          inputs:
            - name: source-repo
          outputs:
            - name: image
          run:
            path: sh
            args:
              - -c
              - |
                cd source-repo
                go build -o ../image/ksvc ./cmd/ksvc

      - put: container-image
        params:
          image: image/ksvc
