global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kubric-ksvc'
    static_configs:
      - targets: ['ksvc:8080']
  - job_name: 'kubric-vdr'
    static_configs:
      - targets: ['vdr:8081']
  - job_name: 'kubric-kic'
    static_configs:
      - targets: ['kic:8082']
  - job_name: 'kubric-noc'
    static_configs:
      - targets: ['noc:8083']
  - job_name: 'kubric-kai'
    static_configs:
      - targets: ['kai:8100']
  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222']
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:9363']
