apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubric-security

resources:
  - namespace.yaml
  - wazuh-manager.yaml
  - velociraptor.yaml
  - thehive.yaml
  - cortex.yaml
  - falco-daemonset.yaml

commonLabels:
  app.kubernetes.io/part-of: kubric
  app.kubernetes.io/managed-by: argocd
