apiVersion: v1
kind: Namespace
metadata:
  name: kubric-security
  labels:
    app.kubernetes.io/part-of: kubric
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
