apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: kubric-ksvc-chaos
  namespace: kubric
spec:
  appinfo:
    appns: kubric
    applabel: app.kubernetes.io/name=ksvc
    appkind: deployment
  engineState: active
  chaosServiceAccount: litmus-admin
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "30"
            - name: CHAOS_INTERVAL
              value: "10"
            - name: FORCE
              value: "false"
            - name: PODS_AFFECTED_PERC
              value: "50"
