apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: noc-nats-partition
  namespace: kubric
spec:
  action: partition
  mode: all
  selector:
    namespaces: [kubric]
    labelSelectors:
      app.kubernetes.io/name: noc
  direction: both
  target:
    selector:
      namespaces: [kubric]
      labelSelectors:
        app.kubernetes.io/name: nats
    mode: all
  duration: "30s"
  scheduler:
    cron: "@every 10m"
