---
global:
  writeToFile: true
  metricsDirectory: /tmp/kube-burner-metrics
  measurements:
    - name: podLatency
      thresholds:
        - conditionType: Ready
          metric: P99
          threshold: 5000ms

jobs:
  - name: kubric-load-test
    jobType: create
    jobIterations: 100
    qps: 20
    burst: 20
    namespacedIterations: false
    namespace: kubric-loadtest
    waitWhenFinished: true
    podWait: false
    objects:
      - objectTemplate: pod-template.yaml
        replicas: 1
        inputVars:
          containerImage: busybox:1.36
