# Kubric API Reference

## Kubric Gateway v1.0 (OpenAPI 3.0.0)

```yaml
openapi: 3.0.0
info:
  title: Kubric Security Platform API
  version: 1.0.0
  description: Unified API gateway for the Kubric security platform
  contact:
    name: Kubric Support
    url: https://kubric.io/support

servers:
  - url: https://api.kubric.io/v1
    description: Production API
  - url: https://staging-api.kubric.io/v1
    description: Staging API

paths:
  /health:
    get:
      operationId: getHealth
      summary: Health check endpoint
      tags:
        - System
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [healthy, degraded, unhealthy]
                  version:
                    type: string
                  uptime_seconds:
                    type: integer

  /incidents:
    get:
      operationId: listIncidents
      summary: List all incidents
      tags:
        - Incidents
      parameters:
        - name: severity
          in: query
          schema:
            type: string
            enum: [P1, P2, P3, P4]
        - name: limit
          in: query
          schema:
            type: integer
            default: 100
      responses:
        '200':
          description: List of incidents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Incident'

    post:
      operationId: createIncident
      summary: Create a new incident
      tags:
        - Incidents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateIncidentRequest'
      responses:
        '201':
          description: Incident created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Incident'

  /incidents/{incidentId}:
    get:
      operationId: getIncident
      summary: Get incident details
      tags:
        - Incidents
      parameters:
        - name: incidentId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Incident details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Incident'
        '404':
          description: Incident not found

  /agents:
    get:
      operationId: listAgents
      summary: List all registered agents
      tags:
        - Agents
      responses:
        '200':
          description: List of agents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Agent'

  /agents/register:
    post:
      operationId: registerAgent
      summary: Register a new agent
      tags:
        - Agents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterAgentRequest'
      responses:
        '201':
          description: Agent registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Agent'

  /billing/usage:
    get:
      operationId: getUsage
      summary: Get usage metrics for billing
      tags:
        - Billing
      parameters:
        - name: start_date
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: end_date
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Usage metrics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsageMetrics'

components:
  schemas:
    Incident:
      type: object
      required:
        - id
        - title
        - severity
        - status
        - created_at
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          maxLength: 255
        description:
          type: string
        severity:
          type: string
          enum: [P1, P2, P3, P4]
        status:
          type: string
          enum: [created, triaged, in-remediation, resolved, closed]
        iocs:
          type: array
          items:
            type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        triage_result:
          $ref: '#/components/schemas/TriageResult'

    CreateIncidentRequest:
      type: object
      required:
        - title
        - severity
      properties:
        title:
          type: string
        description:
          type: string
        severity:
          type: string
          enum: [P1, P2, P3, P4]
        source:
          type: string

    Agent:
      type: object
      required:
        - id
        - hostname
        - blake3_fingerprint
        - status
      properties:
        id:
          type: string
          format: uuid
        hostname:
          type: string
        blake3_fingerprint:
          type: string
          format: hex
        status:
          type: string
          enum: [healthy, degraded, offline]
        last_heartbeat:
          type: string
          format: date-time
        version:
          type: string

    RegisterAgentRequest:
      type: object
      required:
        - install_token
        - hostname
        - blake3_fingerprint
      properties:
        install_token:
          type: string
        hostname:
          type: string
        blake3_fingerprint:
          type: string
          format: hex
        csr_pem:
          type: string
          format: byte

    TriageResult:
      type: object
      properties:
        severity:
          type: integer
          minimum: 1
          maximum: 4
        confidence:
          type: number
          format: float
          minimum: 0
          maximum: 1
        recommendations:
          type: array
          items:
            type: string

    UsageMetrics:
      type: object
      properties:
        period_start:
          type: string
          format: date
        period_end:
          type: string
          format: date
        events_ingested:
          type: integer
        incidents_created:
          type: integer
        agents_active:
          type: integer

  securitySchemes:
    apiKey:
      type: apiKey
      name: X-API-Key
      in: header
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api.kubric.io/oauth/token
          scopes:
            read:incidents: Read incident data
            write:incidents: Create and modify incidents
            read:agents: List agents
            admin: Full administrative access

security:
  - apiKey: []
  - oauth2: [read:incidents, read:agents]
```

---

Generated: 2026-02-12
